---
title: "README for nmdp.asom"
author: "Lisa Rein"
date: "2024-10-15"
output: html_document
---

```{r }

# set working directory to R project for nmdp.asom app
# working directory should be wherever app.R is housed:
mydir <- "Z:/consulting/Logan_Brent/nmdp.asom"
setwd(mydir)

list.files(mydir)

# internal app data, sysdata.rda, should be saved in R subfolder:
list.files(paste0(mydir, "/R"))

```


```{r eval = FALSE}

# To run the app:
# Note the internal app data (includes model objects) is large and the initial load could take a while:
library(shiny)
shiny::runApp()

# you should see a message in the console if the app is successfully loading: 'Loading nmdp.asom'

```


```{r}

# Dependent packages should automatically be installed/loaded but just in case,
# app dependencies (also noted in NAMESPACE):

# export(run_app)
# import(bslib)
# import(flextable)
# import(ggplot2)
# import(nftbart)
# import(shiny)
# import(shinyBS)
# import(shinyjs)
# import(waiter)
# importFrom(golem,activate_js)
# importFrom(golem,add_resource_path)
# importFrom(golem,bundle_resources)
# importFrom(golem,favicon)
# importFrom(golem,with_golem_options)
# importFrom(shiny,HTML)
# importFrom(shiny,NS)
# importFrom(shiny,column)
# importFrom(shiny,shinyApp)
# importFrom(shiny,tagAppendAttributes)
# importFrom(shiny,tagList)
# importFrom(shiny,tags)

```
