---
title: "ASOM (Age/Sex Optimal Matching) Predictions"
date: "`r Sys.Date()`"
output:
  html_document: default
  # pdf_document: default
params:
  ptbl1_os: NA
  plot1_os: NA
  ptbl1_efs: NA
  plot1_efs: NA
  ptbl3_os: NA
  plot3_os: NA
  ptbl3_efs: NA
  plot3_efs: NA
  patprofile: NA
  dat_fmtfun: NA
---

# 1-Year Survival Estimates:

## 1-Year Overall Survival:

```{r echo = FALSE}

params$plot3_os

```

####

```{r echo = FALSE}

library(flextable)
library(knitr)

# flextable(params$ptbl_os) |>
#     flextable::width(j = 1, width = 1) |>
#     flextable::width(j = 2:3, width = 2)

kable(params$ptbl3_os)

```


####

## 1-Year Event-Free Survival:

```{r echo = FALSE}

params$plot3_efs

```

####

```{r echo = FALSE}

# flextable(params$ptbl_os) |>
#     flextable::width(j = 1, width = 1) |>
#     flextable::width(j = 2:3, width = 2)

kable(params$ptbl3_efs)

```

####

# 3-Year Survival Estimates:

## 3-Year Overall Survival:

```{r echo = FALSE}

params$plot3_os

```

####

```{r echo = FALSE}

library(flextable)
library(knitr)

# flextable(params$ptbl_os) |>
#     flextable::width(j = 1, width = 1) |>
#     flextable::width(j = 2:3, width = 2)

kable(params$ptbl3_os)

```


####

## 3-Year Event-Free Survival:

```{r echo = FALSE}

params$plot3_efs

```

####

```{r echo = FALSE}

# flextable(params$ptbl_os) |>
#     flextable::width(j = 1, width = 1) |>
#     flextable::width(j = 2:3, width = 2)

kable(params$ptbl3_efs)

```

#### 

# Patient characteristics:

```{r echo = FALSE}

vnames <- c("age"
,"male"
,"racegp"
,"ethnicit"
,"karnofraw"
,"coorgscore"
,"median_income"
,"rcmvpos"
,"venthxpr"
,"funghxpr"
,"priauto"
,"disease"
,"philgp"
,"allsubgp"
,"cytogeneall"
,"bcrrespr"
,"aldist"
,"indcycle"
,"cytogeneaml"
,"mdstfaml"
,"amlrxrel"
,"clldist"
,"cll17pab"
,"cmldist"
,"ipssrpr"
,"mdspredisp"
,"mdsrxrel"
,"mmissdsdx"
,"mmcytorisk"
,"mmdist"
,"lymresist"
,"lymsubgp"

,"indxtx"
,"yeartx"
,"condclas"
,"tbigp"
,"graftgp"
,"gvhprhrx"
,"invivotcd"
)


```

```{r echo = FALSE}

# dat_fmtfun <- readRDS("../data/dat_fmtfun.RDS")
dat_fmtfun <- params$dat_fmtfun

patdat <- dat_fmtfun(params$patprofile)

patdat <- patdat[,vnames]

x <- data.frame(t(patdat))
names(x) <- "value"

x$vname <- row.names(x)

x$vlab <- NA
for (i in 1:nrow(x)){
   if (!is.null(attr(patdat[,x$vname[i]], "label"))){
      x$vlab[i] <- attr(patdat[,x$vname[i]], "label")
   }
}

x <- subset(x, !(value %in% c("-1", "", NA)))
x <- subset(x, !(vname %in% c("yeartx")))
x <- subset(x, !(vlab %in% c("", NA)))

x <- x[,c("vlab", "value")]
names(x) <- c("Patient Characteristic"
              , "Selected"
              )
kable(x
      ,row.names = FALSE
      )


# flextable(x) |>
#     flextable::width(j = 1:2, width = 2.5) 

```


